### ISSUE TITLE
Latest version breaks 

### ISSUE THREAD

**Issue by middle-aged-man** [zont/gulp-usemin#137]
/node_modules/gulp-usemin/lib/htmlBuilder.js
ReferenceError: Promise is not defined

Looks like you forgot to define Promise when you removed the Q var?

**Comment by pokono** [comment]
+1 Just brought offline all my staging servers.

**Comment by dg1202** [comment]
+1

**Comment by zont** [comment]
Fixed readme

**Comment by jordics** [comment]
Update your node version > 0.12

**Comment by worldspawn** [comment]
I got this with < 0.12 and after going to v4.2.1 i still get it

```
ReferenceError: Promise is not defined
    at C:\Users\sam.critchley\Source\health-canada-reporting\src\RBH.HealthCanadaReporting.FrontEnd\node_modules\gulp-usemin\lib\htmlBuilder.js:20:16
```

**Comment by worldspawn** [comment]
Problem was me. I had `node -v` reporting 4.2.1 but when i ran `gulp` it using some old install which was targeting old node.

Point about your package.json still holds though i think.
