### ISSUE TITLE
0.3.8 and 0.3.9 can not work

### ISSUE THREAD

**Issue by blackbing** [zont/gulp-usemin#89]
I got error while using 0.3.9/0.3.8. 
Here is my config:
```coffee
gulp.task "usemin", ->
  gulp.src("app/*.html")
  .pipe( $.usemin(
    css: [$.csso(), $.minifyCss(), 'concat', $.rev()]
    html: [$.minifyHtml(empty: false)]
    js: [$.uglify(), $.rev()]
  ))
  .pipe(gulp.dest("dist"))
  .pipe $.size()
```
This is Error response.
```shell
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
  at writeAfterEnd (_stream_writable.js:133:12)
  at Transform.Writable.write (_stream_writable.js:181:5)
  at Stream.ondata (stream.js:51:26)
  at Stream.emit (events.js:95:17)
  at Stream.endStream (./node_modules/gulp-usemin/node_modules/gulp-concat/index.js:90:10)
  at _end (./node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:65:9)
  at Stream.stream.end (./node_modules/gulp-usemin/node_modules/gulp-concat/node_modules/through/index.js:74:5)
  at Transform.onend (./node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at Transform.g (events.js:180:16)
  at Transform.emit (events.js:117:20)
  at ./node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:442:13)
```

However, it works well when I point to 0.3.7

**Comment by zont** [comment]
Please check it on v.0.3.10

**Comment by zevero** [comment]
Had the same issue and it doesnt work on v0.3.11 either

    stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
    Error: write after end
      at writeAfterEnd (/home/severin/node/mlt/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
      at DestroyableTransform.Writable.write (/home/severin/node/mlt/node_modules/gulp-minify-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
      at Stream.ondata (stream.js:51:26)
      at Stream.emit (events.js:95:17)
      at Stream.endStream (/home/severin/node/mlt/node_modules/gulp-concat/index.js:90:10)
      at _end (/home/severin/node/mlt/node_modules/gulp-concat/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/severin/node/mlt/node_modules/gulp-concat/node_modules/through/index.js:74:5)
      at Transform.onend (/home/severin/node/mlt/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
      at Transform.g (events.js:180:16)
      at Transform.emit (events.js:117:20)
      at /home/severin/node/mlt/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
      at process._tickCallback (node.js:442:13)

my workaround is to dissable the css section and to not minifyCss

    .pipe(usemin({
      //css: [minifyCss({keepSpecialComments: 0}), 'concat'],

**Comment by zont** [comment]
Looks like some plugin ended stream and after another write to stream

**Comment by jensklose** [comment]
Check your "gulp-minify-css": "0.3.11" version.
I've downgraded to the 0.3.11. Strange errors and weak quality in the last days ...

**Comment by richleland** [comment]
We found that locking down gulp-minify-css to 0.3.11 and gulp-usemin to 0.3.8 eliminates this problem for us. If we bump either library beyond that, we get the `Unhandled stream error in pipe` message.

**Comment by zevero** [comment]
Yes, I did the same thing and arrived at gulp-minify-css to 0.3.11 and gulp-usemin to 0.3.8
BUT: the minified css does not work in my application!
I did not have time to test other combinations of versions and just deactivated css-minifcation for now.

**Comment by arturokunder** [comment]
Same problem around here..but fixing versions as described by @zevero worked for my.
Maybe this is related to [issue 56](https://github.com/jonathanepollack/gulp-minify-css/issues/56) in gulp-minify-css reported a couple of days ago with their latest release

**Comment by richleland** [comment]
@arturokunder thanks for sharing that issue - we use typography.com so that might be related to our issue as well. However, it's worth noting that I encountered this error even when I commented out my css line and was failing on js, specifically as soon as I did this:

`js: [ngAnnotate(), 'concat']` it would bomb out.

**Comment by ppoo24** [comment]
+1 annoyed

**Comment by joshkel** [comment]
Possible duplicate of issue 91. The fix there (giving each block a unique ID and duplicating their configs in my usemin invocation) fixed the error here for me without pinning to 0.3.8.

**Comment by fedotxxl** [comment]
+1

**Comment by zevero** [comment]
Yesterday I switched to gulp 3.9.0 and gulp-usemin 0.3.8 stopped returning.

I finally switched to gulp-useref.
The switch took only a couple of minutes.
Switching assets, restoring streams and using gulp-if seemed to me strange at first, but it turned out to be very easy and intuitive!

**Comment by amoratti** [comment]
+1
Went back to 0.3.8 and had to disable gulp-minify-css and gulp-minify-html

**Comment by zont** [comment]
Fixed in 0.3.14

**Comment by josebarragan** [comment]
Still fails in version 0.3.14.
When back to 0.3.8, works fine with latest versions of gulp and gulp-minify-css

**Comment by timdp** [comment]
+1 for switching to gulp-useref as suggested by @zevero.

**Comment by zont** [comment]
Can you make test (pull request with test)?

**Comment by gregoralbrecht** [comment]
Same here, fails in version 0.3.14 but 0.3.8 works like a charm.

**Comment by chovy** [comment]
still happens for me on latest.

**Comment by hoyangtsai** [comment]
same here, not resolved in 0.3.14

**Comment by samvloeberghs** [comment]
+1

**Comment by WilixLead** [comment]
+1

**Comment by liyunsheng** [comment]
use the second way in the doc, the error doesn't happen.
```
gulp.task('usemin', function() {
  return gulp.src('./*.html')
    .pipe(usemin({
      css: [ rev ],
      html: [ function () {return minifyHtml({ empty: true });} ],
      js: [ uglify, rev ],
      inlinejs: [ uglify ],
      inlinecss: [ minifyCss, 'concat' ]
    }))
    .pipe(gulp.dest('build/'));
});
```

**Comment by the3drevolution** [comment]
+1 for using the second way in the doc, works for me !
