### ISSUE TITLE
gulp-usemin 0.3.9 breaks with: (node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by alocher** [zont/gulp-usemin#97]
I've updated gulp-usemin from 0.3.8 to 0.3.9 and started to receive the following warning/error (same problem with 0.3.11). After going back to 0.3.8 everything works fine again.

```javascript
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Stream.addListener (events.js:160:15)
    at Stream.pipe (stream.js:71:12)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\pipeline.js:26:27
    at Array.forEach (native)
    at module.exports (C:\work\tatool-web\node_modules\gulp-usemin\lib\pipeline.js:25:9)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:35:9
    at Function.promise (C:\work\tatool-web\node_modules\Q\q.js:642:9)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:21:14
    at Array.map (native)
    at module.exports (C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:20:25)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Stream.addListener (events.js:160:15)
    at Stream.pipe (stream.js:71:12)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\pipeline.js:26:27
    at Array.forEach (native)
    at module.exports (C:\work\tatool-web\node_modules\gulp-usemin\lib\pipeline.js:25:9)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:27:9
    at Function.promise (C:\work\tatool-web\node_modules\Q\q.js:642:9)
    at C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:21:14
    at Array.map (native)
    at module.exports (C:\work\tatool-web\node_modules\gulp-usemin\lib\htmlBuilder.js:20:25)

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write after end
    at writeAfterEnd (C:\work\tatool-web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:144:
12)
    at DestroyableTransform.Writable.write (C:\work\tatool-web\node_modules\gulp-minify-css\node_modules\through2\node_modules\readable-stream\lib\_s
tream_writable.js:192:5)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:117:20)
    at Stream.endStream (C:\work\tatool-web\node_modules\gulp-concat\index.js:52:12)
    at _end (C:\work\tatool-web\node_modules\gulp-concat\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\work\tatool-web\node_modules\gulp-concat\node_modules\through\index.js:74:5)
    at Transform.onend (C:\work\tatool-web\node_modules\gulp-usemin\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10
)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
```

My two tasks using usemin look as follows:
```javascript
gulp.task('usemin-app', ['clean'], function() {
  gulp.src('./app/index.html')
    .pipe(usemin({
      css: [minifyCSS(), 'concat'],
      js: [uglify(), 'concat']
    }))
    .pipe(gulp.dest('./dist/'));
});

gulp.task('usemin-module', ['clean'], function() {
  gulp.src('./app/views/module/index.html')
    .pipe(usemin({
      css: [minifyCSS(), 'concat'],
      js: [uglify(), 'concat']
    }))
    .pipe(gulp.dest('./dist/views/module/'));
});
```

**Comment by Mr-Antivirus** [comment]
I have the same issue. I went back to 0.3.8 to get things working, but I added CSS and HTML minifying recently. Since CSS minifying doesn't work with 0.3.8 (produces empty file), but works in 0.3.11, I need 0.3.11 to continue minifying. Anyone have a clue on what is causing this and if so, can you create a pull request for it?

**Comment by Amparose** [comment]
I'm getting same warning on gulp-usemin@0.3.11. 

I've never been able to get JS minification to work with usemin so I would also be keen to see that fixed.

**Comment by lmauri** [comment]
Yes, same issues with last release. All works fine with 0.3.8.

In my case, it does not work js minification (i've 2 js pipeline, only one's resolved) and does not work html when specify *.html and not single file.

**Comment by jedgueruela** [comment]
I am using 0.3.8 as well. It was working fine the first time, but after I re-install my ubuntu, gulp etc then clone my app from my repo ... it's no longer working. Does the gulp version have to do with this ?

**Comment by dholth** [comment]
I had several sections with the same identifier. This kills the plugin. As has been mentioned before multiple input .html also kill the plugin.

```
    <!-- build:css css/bootstrap.min.css -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- endbuild -->

    <!-- build:css css/app.css -->
    <link rel="stylesheet" href="css/app.css">
    <!-- endbuild -->
```

A workaround is to give each `<!-- build -->` comment a unique pipeline id, and a duplicate config inside the gulpfile.

```
    <!-- build:css1 css/bootstrap.min.css -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- endbuild -->

    <!-- build:css3 css/app.css -->
    <link rel="stylesheet" href="css/app.css">
    <!-- endbuild -->
```

```
    .pipe(usemin({
        css1: [minifyCss(), 'concat'],
        css3: [minifyCss(), 'concat'],
...
```

Instead, it would be great if, instead of crashing, multiple ```<!-- build:name -->``` comments would reference the same pipeline configuration.

**Comment by joshkel** [comment]
@dholth's solution works for me as well. This appears to be the same root issue as #91.

**Comment by lizhong8532** [comment]
I had this issue, too

**Comment by lizhong8532** [comment]
but I down version to 0.3.8 then fix this bug

**Comment by mcometa** [comment]
This happened to me too but I don't have multiple ` in my source html. I used [gulp-foreach](https://www.npmjs.com/package/gulp-foreach) to handle the files one by one. Also this gulp block that I have gives a nice log from the Terminal.

![[https://cloud.githubusercontent.com/assets/66358/7316108/9f2b27e6-eaa6-11e4-8ff2-8d2d6a41020c.png|width=100px]]

```
gulp.task('build:html', function(){
	return gulp.src('src/*.html')
		.pipe($.fileInclude())
		.pipe(gulp.dest('tmp/'))
		.pipe($.foreach(function(stream, file){
			var filePath = file.path,
				file = filePath.substring(filePath.lastIndexOf('/')+1);
			$.util.log('Processing ' + $.util.colors.yellow(file) + '...');
			return stream
				.pipe($.usemin({
					css: [$.csso()],
					js: [$.uglify(), $.header(banner,{pkg:pkg, date:date})]
				}));
		}))
		.pipe(gulp.dest('dist/'));
});
```

**Comment by korprulu** [comment]
You can add one line at the beginning of gulp.js
`require('events').EventEmitter.defaultMaxListeners = 0;`

Refer to https://nodejs.org/api/all.html#all_eventemitter_defaultmaxlisteners

**Comment by brutaldev** [comment]
@mcometa The [gulp-foreach](https://www.npmjs.com/package/gulp-foreach) solution works like a charm, thanks!

**Comment by zont** [comment]
Fixed in 0.3.14

**Comment by samvloeberghs** [comment]
Don't think it's fixed yet. I've switched to 0.3.8 and that made it work.
